server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flight?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123
